# Generated by Django 3.0 on 2022-06-24 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0019_auto_20220623_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='week_start',
            field=models.DateField(db_column='_week_start', default=django.utils.timezone.now),
        ),
    ]
