# Generated by Django 3.0 on 2022-06-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0020_master_db_week_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_db',
            name='week_start',
        ),
    ]
