# Generated by Django 3.0 on 2022-06-27 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0021_remove_master_db_week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='_week_start',
            field=models.DateField(db_column='week_start', default=django.utils.timezone.now),
        ),
    ]
