# Generated by Django 3.0 on 2022-06-27 14:47

import computed_property.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0023_remove_master_db__week_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_db',
            name='_week_start',
            field=computed_property.fields.ComputedDateField(compute_from='week_start', default=django.utils.timezone.now, editable=False),
        ),
    ]
